apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prasad-moru/gitops-repo.git'
    path: environments/production/nginx-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prasad-moru/gitops-repo.git'
    path: environments/staging/nginx-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prasad-moru/gitops-repo.git'
    path: environments/dev/nginx-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
