apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  clusterIP: None
  selector:
    app: nginx
